insert into cliente (id, nome, data_nascimento, status) values (1, 'Luna Milena Moura', '2010-09-13', 'ATIVO');
insert into cliente (id, nome, data_nascimento, status) values (2, 'Thomas Julio Gustavo', '2015-05-13', 'INATIVO');
insert into cliente (id, nome, data_nascimento, status) values (3, 'Eliane Cecília Pires', '2000-02-13', 'ATIVO');
insert into cliente (id, nome, data_nascimento, status) values (4, 'Nicole Aline Eliane da Conceição', '1989-02-13', 'INATIVO');
insert into cliente (id, nome, data_nascimento, status) values (5, 'Aline Eduarda Isabel de Paula', '1950-04-13', 'INATIVO');
insert into cliente (id, nome, data_nascimento, status) values (6, 'Eduardo Nathan Pereira', '1953-02-13', 'ATIVO');
insert into cliente (id, nome, data_nascimento, status) values (7, 'Elias Roberto Renato Caldeira', '1999-09-13', 'ATIVO');
insert into cliente (id, nome, data_nascimento, status) values (8, 'Mário Márcio Geraldo Brito', '2002-09-13', 'INATIVO');
insert into cliente (id, nome, data_nascimento, status) values (9, 'Rosa Francisca Bernardes', '2003-08-13', 'ATIVO');
insert into cliente (id, nome, data_nascimento, status) values (10, 'Nicole Cláudia', '1923-07-13', 'INATIVO');
insert into cliente (id, nome, data_nascimento, status) values (11, 'Lucas José Davi', '1970-06-13', 'ATIVO');
insert into cliente (id, nome, data_nascimento, status) values (12, 'Anderson Lucca Lopes', '1974-05-13', 'INATIVO');
insert into cliente (id, nome, data_nascimento, status) values (13, 'Pietra Marina Mariah Viana', '1976-01-13', 'INATIVO');
insert into cliente (id, nome, data_nascimento, status) values (14, 'Victor Kevin Santos', '1978-02-13', 'ATIVO');
insert into cliente (id, nome, data_nascimento, status) values (15, 'Lívia Clara Mariane Fernandes', '1995-03-13', 'ATIVO');
